### ISSUE TITLE
more consistency - rename language to langcode

### ISSUE THREAD

**Issue by MoniqueHahnefeld** [MetaModels/attribute_translatedurl#3]
in the other translated attributes the langcode field is named langcode. so it will be more consistently if the field  has the same name. Further the field is limited to 2 letters. It should be limited to 5 letters.
May I make a PR this Issue @discordier @cboelter @MetaModels/team :)?

**Comment by discordier** [comment]
You may file apull request but keep in mind that you have to alter the existing databases and rename the field if it exists.
In the end, I wonder if it is worth the hassle as we have plenty of more important stuff to work on.

The field size however could be changed to 5 chars without problems in a separate PR.

**Comment by MoniqueHahnefeld** [comment]
yes it comes to my mind while i was working with this attribute. will code the PR next time :) master @discordier
