### ISSUE TITLE
Error on Metamodel new entry when having a translated url field

### ISSUE THREAD

**Issue by klickagent** [MetaModels/attribute_translatedurl#5]
We have installed Contao 3.2.21 and are using MetaModels/attribute_translatedurl 2.0.0-alpha1.

When I try to add a new content to one of the Metamodels which has a translated url field the error page "Es ist ein Fehler aufgetreten" is shown. The error_log shows the following error:

`PHP Fatal error: Uncaught exception 'Exception' with message 'Query error: Column 'href' cannot be null (INSERT INTO tl_metamodel_translatedurl (att_id, item_id, language, tstamp, href, title) VALUES ('30',49,'de',1465828579,NULL,NULL))' thrown in /html/system/modules/core/library/Contao/Database/Statement.php on line 279`

To reproduce:
Setup a metamodel and add a translated url field. Then go to the content of the meatmodel and try to add an element.

Thanks for your help.
Roman

**Comment by zonky2** [comment]
pls consider
http://metamodels.readthedocs.io/en/latest/manual/install.html#install-and-update-metamodels
>You will need a Contao-LTS-version to be able to install MetaModels - **the current version is Contao 3.5.x**

**Comment by discordier** [comment]
@zonky2 could you please check if the problem persists in the current version?

**Comment by zonky2** [comment]
Test: C 3.5.12, MM core a11, MM transurl a1, DCG b36

=> works fine...

![shot241](https://cloud.githubusercontent.com/assets/1045318/16033389/04b4a8dc-320c-11e6-989a-7ae476575471.jpg)

![shot242](https://cloud.githubusercontent.com/assets/1045318/16033391/0c4ee44a-320c-11e6-9c11-7d06ebdf4c5d.jpg)

![shot243](https://cloud.githubusercontent.com/assets/1045318/16033398/15853898-320c-11e6-8299-8aa2663df929.jpg)

**Comment by discordier** [comment]
If it works, it is rather invalid than testing. Testing is only for tickets where something has been fixed.

**Comment by zonky2** [comment]
o.k.

**Comment by kwissy** [comment]
Just to say... it still trows the error with the latest build.

**Comment by discordier** [comment]
@kwissy We will need the exact configuration otherwise we can not be of help.

Your fix is definately wrong, as href must not be null, it is mandatory (at least it was intended to be like this).

**Comment by kwissy** [comment]
I know that the fix is just a quick and dirty workaround and not meant in productive environments.

It's the nightly build from 14th of july 2016, the complete thing. It happens only when i want to add a new record to the list, of course a new record can not have a href already set. I get an error but the record will still be created and i can edit it after i refreshed the page.

Don't get why this should be mandatory, you can definitly have some records without href.

Anyway, so far more than just great work guys.

**Comment by dennishpunkt** [comment]
@discordier I have the same issue using a translated url field. If the href field is empty a  NULL value is trying to be saved in the 'href' column of the database table and an error is thrown, cause NULL isn't allowed here.

I'm using this field in combination with a visibility condition, so an empty value for href should be allowed.

And empty value should not be saved as NULL, but as an empty string.

If you need more information, just text me.

**Comment by zonky2** [comment]
@discordier what is the reason to save a empty value as ```null``` `https://github.com/MetaModels/attribute_translatedurl/blob/master/src/MetaModels/Attribute/TranslatedUrl/TranslatedUrl.php#L226

**Comment by zonky2** [comment]
its fixed and closed with https://github.com/MetaModels/attribute_translatedurl/pull/8
